const ErrorCodes = {
    AUTH: {
        INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
        ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
        EMAIL_EXISTS: 'EMAIL_EXISTS',
    },
    USER: {
        NOT_FOUND: 'USER_NOT_FOUND',
    },
    VALIDATION: {
        INVALID_EMAIL: 'INVALID_EMAIL',
        MISSING_FIELDS: 'MISSING_FIELDS',
    },
    INTERNAL: 'INTERNAL_SERVER_ERROR'
};

module.exports = ErrorCodes;