const MessageCodes = {
    AUTH: {
        INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
        ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
        EMAIL_EXISTS: 'EMAIL_EXISTS',
        REFRESH_TOKEN_INVALID: 'REFRESH_TOKEN_INVALID',
        REFRESH_TOKEN_EXPIRED: 'REFRESH_TOKEN_EXPIRED',
        TOKEN_REFRESHED: 'TOKEN_REFRESHED',
        USER_REGISTERED: 'USER_REGISTERED',
        LOGGED_IN: 'LOGGED_IN',
        AUTH_TOKEN_MISSING: 'AUTH_TOKEN_MISSING',

    },
    USER: {
        NOT_FOUND: 'USER_NOT_FOUND',
        CURRENT_USER: 'CURRENT_USER',
    },
    VALIDATION: {
        INVALID_EMAIL: 'INVALID_EMAIL',
        MISSING_FIELDS: 'MISSING_FIELDS',
    },
    INTERNAL: 'INTERNAL_SERVER_ERROR'
};

module.exports = MessageCodes;